// <auto-generated />
using System;
using HaritaWeb.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaritaWeb.UI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250801140237_hotspots2")]
    partial class hotspots2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("HaritaWeb.Entities.Models.Harita", b =>
                {
                    b.Property<int>("HaritaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("DosyaTipi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaritaAdı")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MahalleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HaritaId");

                    b.HasIndex("KategoriId");

                    b.HasIndex("MahalleId")
                        .IsUnique();

                    b.ToTable("Harita");

                    b.HasData(
                        new
                        {
                            HaritaId = 1,
                            Aciklama = "",
                            DosyaTipi = ".pdf",
                            DosyaYolu = "https://cbs.kayseri.bel.tr/PDF/KAYSERI_BUYUKSEHIR_BELEDIYE_SINIRI.pdf",
                            HaritaAdı = "Kayseri_Buyuksehir_Belediye_Sınırı",
                            KategoriId = 1
                        },
                        new
                        {
                            HaritaId = 2,
                            Aciklama = "",
                            DosyaTipi = ".jpg",
                            DosyaYolu = "https://cbs.kayseri.bel.tr/dosya/cbs/harita/KayseriIlHaritasi2019.jpg",
                            HaritaAdı = "Kayseri_İl_Sınırı_2020",
                            KategoriId = 2
                        },
                        new
                        {
                            HaritaId = 3,
                            Aciklama = "",
                            DosyaTipi = ".pdf",
                            DosyaYolu = "https://cbs.kayseri.bel.tr/PDF/KENT_REHBERI_1_5000_OLCEKLI_1400X3500_BOYUTLU_2025.PDF",
                            HaritaAdı = "KENT_REHBERI_1_5000_OLCEKLI_1400X3500_BOYUTLU_2025",
                            KategoriId = 3
                        },
                        new
                        {
                            HaritaId = 4,
                            Aciklama = "",
                            DosyaTipi = ".pdf",
                            DosyaYolu = "https://cbs.kayseri.bel.tr/PDF/KENT_REHBERI_1_7500_OLCEKLI_900X2850_BOYUTLU_GUNEY_2025.PDF",
                            HaritaAdı = "KENT_REHBERI_1_7500_OLCEKLI_900X2850_BOYUTLU_GUNEY_2025",
                            KategoriId = 3
                        });
                });

            modelBuilder.Entity("HaritaWeb.Entities.Models.Hotspots", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PanoramaId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Pitch")
                        .HasColumnType("REAL");

                    b.Property<int?>("TargetPanoramaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<float>("Yaw")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PanoramaId");

                    b.HasIndex("TargetPanoramaId");

                    b.ToTable("Hotspots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PanoramaId = 1,
                            Pitch = -2.0277f,
                            TargetPanoramaId = 2,
                            Text = "Büyükşehir Belediyesi",
                            Type = "scene",
                            Yaw = 98.4969f
                        },
                        new
                        {
                            Id = 2,
                            PanoramaId = 1,
                            Pitch = -5.9475f,
                            TargetPanoramaId = 5,
                            Text = "Ali Dağı",
                            Type = "scene",
                            Yaw = 164.5426f
                        });
                });

            modelBuilder.Entity("HaritaWeb.Entities.Models.Ilce", b =>
                {
                    b.Property<int>("IlceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IlceId");

                    b.ToTable("Ilce");

                    b.HasData(
                        new
                        {
                            IlceId = 2,
                            IlceAdi = "Akkışla"
                        },
                        new
                        {
                            IlceId = 3,
                            IlceAdi = "Bünyan"
                        },
                        new
                        {
                            IlceId = 4,
                            IlceAdi = "Develi"
                        },
                        new
                        {
                            IlceId = 5,
                            IlceAdi = "Felahiye"
                        },
                        new
                        {
                            IlceId = 6,
                            IlceAdi = "Hacılar"
                        },
                        new
                        {
                            IlceId = 7,
                            IlceAdi = "İncesu"
                        },
                        new
                        {
                            IlceId = 8,
                            IlceAdi = "Kocasinan"
                        },
                        new
                        {
                            IlceId = 9,
                            IlceAdi = "Melikgazi"
                        },
                        new
                        {
                            IlceId = 10,
                            IlceAdi = "Özvatan"
                        },
                        new
                        {
                            IlceId = 11,
                            IlceAdi = "Pınarbaşı"
                        },
                        new
                        {
                            IlceId = 12,
                            IlceAdi = "Sarıoğlan"
                        },
                        new
                        {
                            IlceId = 13,
                            IlceAdi = "Sarız"
                        },
                        new
                        {
                            IlceId = 14,
                            IlceAdi = "Talas"
                        },
                        new
                        {
                            IlceId = 15,
                            IlceAdi = "Tomarza"
                        },
                        new
                        {
                            IlceId = 16,
                            IlceAdi = "Yahyalı"
                        },
                        new
                        {
                            IlceId = 17,
                            IlceAdi = "Yeşilhisar"
                        },
                        new
                        {
                            IlceId = 1,
                            IlceAdi = "Sehir Merkezi"
                        });
                });

            modelBuilder.Entity("HaritaWeb.Entities.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KategoriAdı")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KategoriId");

                    b.ToTable("Kategori");

                    b.HasData(
                        new
                        {
                            KategoriId = 1,
                            KategoriAdı = "Kayseri Büyüksehir Belediye Sınırı"
                        },
                        new
                        {
                            KategoriId = 2,
                            KategoriAdı = "Kayseri İl Sınırı 2020"
                        },
                        new
                        {
                            KategoriId = 3,
                            KategoriAdı = "2025 Yılı Kayseri Kent Merkezi ve Çevresi"
                        });
                });

            modelBuilder.Entity("HaritaWeb.Entities.Models.Mahalle", b =>
                {
                    b.Property<int>("MahalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IlceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MahalleAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MahalleId");

                    b.HasIndex("IlceId");

                    b.ToTable("Mahalle");

                    b.HasData(
                        new
                        {
                            MahalleId = 1,
                            IlceId = 1,
                            MahalleAdi = "Alevkışla"
                        },
                        new
                        {
                            MahalleId = 2,
                            IlceId = 1,
                            MahalleAdi = "Akin"
                        },
                        new
                        {
                            MahalleId = 3,
                            IlceId = 1,
                            MahalleAdi = "Ganişeyh"
                        });
                });

            modelBuilder.Entity("HaritaWeb.Entities.Models.Panorama", b =>
                {
                    b.Property<int>("PanoramaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<float?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PanoramaAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PanoramaKategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PanoramaResimYolu")
                        .HasColumnType("TEXT");

                    b.Property<string>("PanoramaYolu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("PanoramaId");

                    b.HasIndex("PanoramaKategoriId");

                    b.ToTable("Panorama");

                    b.HasData(
                        new
                        {
                            PanoramaId = 1,
                            PanoramaAd = "Cumhuriyet Meydanı",
                            PanoramaKategoriId = 1,
                            PanoramaResimYolu = "/img/multires/cumhuriyet_meydanı/cumhuriyetmeydanı.jpg",
                            PanoramaYolu = "/img/multires/cumhuriyet_meydanı/tiles",
                            Tarih = new DateTime(2018, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PanoramaId = 5,
                            PanoramaAd = "Ali Dağı",
                            PanoramaKategoriId = 1,
                            PanoramaResimYolu = "/img/multires/360_drone_alidagtepe/alidağtepe.jpg",
                            PanoramaYolu = "/img/multires/360_drone_alidagtepe/tiles",
                            Tarih = new DateTime(2018, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PanoramaId = 2,
                            PanoramaAd = "Büyükşehir Belediyesi",
                            PanoramaKategoriId = 1,
                            PanoramaResimYolu = "/img/multires/360belediye/buyuksehirbelediye.jpg",
                            PanoramaYolu = "/img/multires/360belediye/tiles",
                            Tarih = new DateTime(2018, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PanoramaId = 4,
                            PanoramaAd = "İncesu Meydan-1",
                            PanoramaKategoriId = 1,
                            PanoramaResimYolu = "/img/multires/360_drone_incesu/incesumeydan.jpg",
                            PanoramaYolu = "/img/multires/360_drone_incesu/tiles",
                            Tarih = new DateTime(2019, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PanoramaId = 3,
                            PanoramaAd = "Bilim Merkezi",
                            PanoramaKategoriId = 3,
                            PanoramaResimYolu = "/img/multires/360_bilim_merkezi/overview_map.jpg",
                            PanoramaYolu = "/img/multires/360_bilim_merkezi/tiles",
                            Tarih = new DateTime(2018, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HaritaWeb.Entities.Models.PanoramaKategori", b =>
                {
                    b.Property<int>("PanoramaKategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IlceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PanoramaKategoriAdı")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PanoramaKategoriId");

                    b.HasIndex("IlceId");

                    b.ToTable("PanoramaKategori");

                    b.HasData(
                        new
                        {
                            PanoramaKategoriId = 1,
                            IlceId = 1,
                            PanoramaKategoriAdı = "Cumhuriyet Meydanı"
                        },
                        new
                        {
                            PanoramaKategoriId = 2,
                            IlceId = 1,
                            PanoramaKategoriAdı = "Büyükşehir Belediyesi"
                        },
                        new
                        {
                            PanoramaKategoriId = 3,
                            IlceId = 1,
                            PanoramaKategoriAdı = "Bilim Merkezi"
                        },
                        new
                        {
                            PanoramaKategoriId = 4,
                            IlceId = 7,
                            PanoramaKategoriAdı = "İncesu Meydan"
                        });
                });

            modelBuilder.Entity("HaritaWeb.Entities.Models.Harita", b =>
                {
                    b.HasOne("HaritaWeb.Entities.Models.Kategori", "Kategori")
                        .WithMany("Haritalar")
                        .HasForeignKey("KategoriId");

                    b.HasOne("HaritaWeb.Entities.Models.Mahalle", "Mahalle")
                        .WithOne("Harita")
                        .HasForeignKey("HaritaWeb.Entities.Models.Harita", "MahalleId");

                    b.Navigation("Kategori");

                    b.Navigation("Mahalle");
                });

            modelBuilder.Entity("HaritaWeb.Entities.Models.Hotspots", b =>
                {
                    b.HasOne("HaritaWeb.Entities.Models.Panorama", "Panorama")
                        .WithMany("Hotspots")
                        .HasForeignKey("PanoramaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HaritaWeb.Entities.Models.Panorama", "TargetPanorama")
                        .WithMany()
                        .HasForeignKey("TargetPanoramaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Panorama");

                    b.Navigation("TargetPanorama");
                });

            modelBuilder.Entity("HaritaWeb.Entities.Models.Mahalle", b =>
                {
                    b.HasOne("HaritaWeb.Entities.Models.Ilce", "Ilce")
                        .WithMany("Mahalleler")
                        .HasForeignKey("IlceId");

                    b.Navigation("Ilce");
                });

            modelBuilder.Entity("HaritaWeb.Entities.Models.Panorama", b =>
                {
                    b.HasOne("HaritaWeb.Entities.Models.PanoramaKategori", "PanoramaKategori")
                        .WithMany()
                        .HasForeignKey("PanoramaKategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PanoramaKategori");
                });

            modelBuilder.Entity("HaritaWeb.Entities.Models.PanoramaKategori", b =>
                {
                    b.HasOne("HaritaWeb.Entities.Models.Ilce", "Ilce")
                        .WithMany()
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilce");
                });

            modelBuilder.Entity("HaritaWeb.Entities.Models.Ilce", b =>
                {
                    b.Navigation("Mahalleler");
                });

            modelBuilder.Entity("HaritaWeb.Entities.Models.Kategori", b =>
                {
                    b.Navigation("Haritalar");
                });

            modelBuilder.Entity("HaritaWeb.Entities.Models.Mahalle", b =>
                {
                    b.Navigation("Harita");
                });

            modelBuilder.Entity("HaritaWeb.Entities.Models.Panorama", b =>
                {
                    b.Navigation("Hotspots");
                });
#pragma warning restore 612, 618
        }
    }
}
